# Generated by Django 5.2.17 on 2026-09-30 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Event', 'Event Staff'), ('Catering', 'Catering'), ('Parking', 'Parking'), ('Cleaning', 'Cleaning'), ('Loading', 'Loading & Unloading'), ('Delivery', 'Delivery'), ('Construction', 'Construction'), ('Technical', 'Technical'), ('Hospitality', 'Hospitality'), ('Photography', 'Photography'), ('Other', 'Other')], max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('workers_required', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(limit_choices_to={'role': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
